import requests
from bs4 import BeautifulSoup
import json
import sys

def scrape_imdb_movies():
    """
    Scrape IMDb for movies with ratings between 3.0 and 5.0
    Returns JSON array with id, title, year, rating
    """
    
    # IMDb advanced search URL
    url = "https://www.imdb.com/search/title/?user_rating=3.0,5.0&sort=user_rating,desc&count=25"
    
    # Headers to avoid being blocked
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
        'Connection': 'keep-alive',
    }
    
    print(f"Fetching movies from IMDb...")
    
    try:
        # Make the request
        response = requests.get(url, headers=headers, timeout=15)
        response.raise_for_status()
        
        # Parse HTML
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Find all movie containers
        movie_items = soup.find_all('div', class_='lister-item mode-advanced')
        
        results = []
        
        for item in movie_items[:25]:  # Limit to 25 items
            try:
                # Extract IMDb ID
                link_tag = item.find('a', href=True)
                if link_tag and '/title/' in link_tag['href']:
                    href = link_tag['href']
                    imdb_id = href.split('/title/')[1].split('/')[0]
                else:
                    continue
                
                # Extract title
                title_tag = item.find('h3', class_='lister-item-header')
                if title_tag:
                    title = title_tag.find('a').text.strip()
                else:
                    continue
                
                # Extract year
                year_tag = item.find('span', class_='lister-item-year')
                if year_tag:
                    year = year_tag.text.strip()
                    # Clean up year (remove parentheses and extra characters)
                    year = year.replace('(', '').replace(')', '').replace('I', '').strip()
                else:
                    year = ''
                
                # Extract rating
                rating_tag = item.find('div', class_='ratings-bar')
                if rating_tag:
                    rating_value = rating_tag.find('strong')
                    rating = rating_value.text.strip() if rating_value else ''
                else:
                    rating = ''
                
                # Only add if we have all required fields
                if imdb_id and title and year and rating:
                    results.append({
                        "id": imdb_id,
                        "title": title,
                        "year": year,
                        "rating": rating
                    })
                    
            except Exception as e:
                print(f"Error parsing item: {e}")
                continue
        
        return results
        
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data: {e}")
        return []

def main():
    """Main function"""
    
    print("="*60)
    print("IMDb Movie Scraper - 23ds3000079@ds.study.iitm.ac.in")
    print("="*60)
    print("Rating Range: 3.0 - 5.0")
    print("="*60)
    
    # Scrape movies
    movies = scrape_imdb_movies()
    
    if movies:
        # Output JSON
        json_output = json.dumps(movies, indent=2)
        print("\n" + json_output)
        
        # Save to file
        with open('imdb_movies.json', 'w') as f:
            f.write(json_output)
        
        print(f"\n✅ Successfully scraped {len(movies)} movies")
        print("📁 Results saved to imdb_movies.json")
        
        # Also save a simple text file with count
        with open('results.txt', 'w') as f:
            f.write(f"IMDb Movies Scraped: {len(movies)}\n")
            f.write(f"Rating Range: 3.0-5.0\n")
            f.write(f"Generated by: 23ds3000079@ds.study.iitm.ac.in\n")
    else:
        print("❌ No movies found")
        sys.exit(1)

if __name__ == "__main__":
    main()
